"""Run the shared CP5 retrieval benchmark on the local corpus.

Replace the five entries in BENCHMARKS with the five questions agreed by the
group. Each entry optionally supplies a metadata filter for A/B comparison.
"""

from __future__ import annotations

import re
from pathlib import Path

from src import Document, EmbeddingStore, HeadingChunker, _mock_embed


DATA_DIR = Path("data/hocbong")
TOP_K = 3

# Each member changes only this line when comparing chunking strategies.
CHUNKER = HeadingChunker(chunk_size=800)

# These are starter queries based on the current corpus. Replace them with the
# five shared, verified questions supplied by the group's benchmark lead.
BENCHMARKS = [
    (
        "Hạn cuối nộp hồ sơ học bổng Trần Đại Nghĩa là khi nào?",
        {"audience": "student"},
    ),
    ("Học bổng MB The Best of MB Chasing có giá trị bao nhiêu?", None),
    ("Thời hạn gửi thắc mắc về kết quả xét học bổng kỳ 2025.2 là khi nào?", None),
    ("Có bao nhiêu sinh viên nhận học bổng khuyến khích học tập loại A?", None),
    ("Biểu mẫu đề nghị điều chỉnh điểm dành cho đối tượng nào?", {"audience": "faculty"}),
]

FILTER_AB_QUERY = "Hạn cuối nộp hồ sơ học bổng Trần Đại Nghĩa là khi nào?"


def read_markdown(path: Path) -> tuple[dict[str, str], str]:
    """Read the YAML-like front matter generated by the course crawler."""
    raw = path.read_text(encoding="utf-8")
    parts = raw.split("---", 2)
    if len(parts) != 3 or parts[0].strip():
        raise ValueError(f"Missing front matter: {path}")

    metadata = {
        key: value.strip().strip('"')
        for key, value in re.findall(r"^(\w+):\s*(.+)$", parts[1], re.MULTILINE)
    }
    return metadata, parts[2].strip()


def load_chunked_documents(data_dir: Path) -> list[Document]:
    """Parse every corpus file and create one Document per chunk."""
    documents: list[Document] = []
    for path in sorted(data_dir.glob("*.md")):
        metadata, content = read_markdown(path)
        metadata["doc_id"] = path.stem
        for index, chunk in enumerate(CHUNKER.chunk(content)):
            documents.append(
                Document(
                    id=f"{path.stem}#{index}",
                    content=chunk,
                    metadata=dict(metadata),
                )
            )
    return documents


def main() -> int:
    if not DATA_DIR.is_dir():
        print(f"Không tìm thấy corpus: {DATA_DIR}")
        return 1

    documents = load_chunked_documents(DATA_DIR)
    if not documents:
        print("Corpus không có chunk để nạp.")
        return 1

    store = EmbeddingStore(collection_name="hocbong_benchmark", embedding_fn=_mock_embed)
    store.add_documents(documents)
    print(f"Đã nạp {store.get_collection_size()} chunks từ {DATA_DIR}.")
    print(f"Chunker: {CHUNKER.__class__.__name__}\n")

    for index, (query, metadata_filter) in enumerate(BENCHMARKS, start=1):
        print(f"Câu {index}: {query}")
        print(f"Filter: {metadata_filter or 'không dùng'}")
        results = store.search_with_filter(query, top_k=TOP_K, metadata_filter=metadata_filter)
        if not results:
            print("  Không có kết quả.")
        for rank, result in enumerate(results, start=1):
            preview = " ".join(result["content"].split())[:180]
            print(
                f"  {rank}. score={result['score']:.3f} "
                f"doc_id={result['metadata'].get('doc_id')}\n"
                f"     {preview}"
            )
        print()

    print("A/B metadata filter (cùng một câu hỏi):")
    for label, metadata_filter in (("không filter", None), ("audience=student", {"audience": "student"})):
        results = store.search_with_filter(FILTER_AB_QUERY, top_k=TOP_K, metadata_filter=metadata_filter)
        doc_ids = [result["metadata"].get("doc_id") for result in results]
        print(f"  {label}: {doc_ids}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
